<?xml version="1.0"?>
<package format="3">
  <name>mjv_robot_fleet_base</name>
  <version>0.0.1</version>
  <description>Base segura para evolução multi-robô do controle de base da MJV.</description>

  <maintainer email="voce@mjv.com">MJV</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>