<?xml version="1.0"?>
<package format="3">
  <name>mjv_ui_bridge</name>
  <version>0.0.1</version>
  <description>Bridge entre UI Web e Nav2</description>
  <maintainer email="mjv@local">mjv</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>

</package>
